####
## This file is managed by puppet, do not change it locally.
##

# User specific aliases and functions

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

# Paths
PATH=$PATH:/sbin:/usr/sbin
export PATH

# Prompt
export PS1="\e[1;31m\u\e[m@\e[0;36m\h\e[m [\[$(tput bold)\]\w\[$(tput sgr0)\]]# "

# Aliases
alias ssh='ssh -A'
alias vi='vim'
alias cls='clear'
alias ll='ls -lh'
alias lla='ls -lah'
alias forcepuppet='sudo su -; /usr/local/scripts/forcepuppet.sh'

alias db='cd /var/lib/mysql'
alias mystop='/sbin/service mysql stop'
alias mystart='/sbin/service mysql start'
alias myrestart='/sbin/service mysql restart'
alias myping='mysqladmin ping'
alias mycnf='vi /var/lib/mysql/etc/my.cnf'
alias myerror='vi /var/lib/mysql/logs/error/mysql-errors.err'

alias myback='cd /var/lib/mysql/backups'
alias mybackup='/var/lib/mysql/scripts/N*'
alias vimyback='vi /var/lib/mysql/scripts/N*'
